[package]
name = "netrunner-client"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
netrunner-core = { path = "../core" }
smoltcp = { version = "0.12", default-features = false, features = [
    "std",
    "log",
    "medium-ip",
    "proto-ipv4",
    "proto-ipv4-fragmentation",
    "proto-ipv6",
    "socket-icmp",
    "socket-udp",
    "socket-tcp",
    "socket-tcp-cubic",
] }
tokio = { version = "1.36", features = ["full"] }
bytes = "1.5"
log = "0.4"
tun = { version = "0.8", features = ["async"] }
lazy_static = "1.4.0"
thiserror = "2.0"
hickory-proto = "0.25.2"
lru = "0.16.3"
tokio-util = "0.7.18"
shlex = "1.3"
uniffi = { version = "0.31.0", features = ["tokio", ] }
reqwest = { version = "0.13.2", features = ["json"] } 
anyhow = "1.0"
netrunner-logger = { path = "../tools/log" }
crossbeam-queue = "0.3.11"

[build-dependencies]
uniffi = { version = "0.31.0", features = ["build"] }


[target.'cfg(target_os = "windows")'.dependencies]
wintun = "0.5.1"

