[package]
name = "netrunner-client"
version = "0.1.0"
edition = "2024"

[[example]]
name = "client_example"
path = "examples/client_example.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
netrunner-common = { path = "../common" } # Наша общая либа
smoltcp = { version = "0.12", default-features = false, features = [
    "std",
    "log",
    "medium-ip",
    "proto-ipv4",
    "proto-ipv4-fragmentation",
    "proto-ipv6",
    "socket-icmp",
    "socket-udp",
    "socket-tcp",
    "socket-tcp-cubic",
] }
tokio = { version = "1.36", features = ["full"] }
jni = "0.21"
bytes = "1.5"
android_logger = "0.13"
log = "0.4"
tun = { version = "0.8", features = ["async"] }
lazy_static = "1.4.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
byte_string = "1.0"
ipnet = "2.10"
spin = { version = "0.10" }
etherparse = { version = "0.19" }
thiserror = "2.0"