use bytes::{BufMut, Bytes, BytesMut};

use crate::{
    tlseng::{
        consts::{HANDSHAKE_TYPE_CLIENT_HELLO, HANDSHAKE_TYPE_SERVER_HELLO},
        extension::ExtensionBuilder,
        profile::BrowserProfile,
        tls_record::TlsRecord,
        types::{ContentType, HelloType, ProtocolVersion},
    },
    utils::u24::U24,
};

pub struct HelloHeader {
    pub header_type: HelloType,
    pub len: U24,
}

pub struct ClientHello {
    /// The maximum version supported (legacy field in TLS 1.3)
    pub version: ProtocolVersion,
    /// 32 bytes of client-generated entropy
    pub random: [u8; 32],
    /// Legacy session ID (used in TLS 1.3 for middlebox compatibility)
    pub session_id: Bytes,
    /// List of cryptographic ciphers the client supports
    pub cipher_suites: Vec<u16>,
    /// Opaque block of extensions generated by ExtensionBuilder
    pub extensions: Bytes,
}

impl ClientHello {
    /// Serializes the ClientHello message into its wire format.
    /// Includes the 4-byte Handshake header (Type + Length).
    pub fn serialize(&self) -> Bytes {
        let mut buf = BytesMut::with_capacity(512 + self.extensions.len());

        // Handshake Type: 0x01 (ClientHello)
        buf.put_u8(HANDSHAKE_TYPE_CLIENT_HELLO);

        // Handshake Length Placeholder:
        // Handshake messages use a 24-bit (3 byte) length field.
        let length_pos = buf.len();
        buf.put_bytes(0, 3);

        // Protocol Version:
        // For TLS 1.3, this is traditionally pinned to 0x0303 (TLS 1.2)
        // to prevent middleboxes from dropping the packet.
        buf.put_u16(0x0303);
        buf.put_slice(&self.random);

        // Legacy Session ID:
        // Formatted as Length (1 byte) + ID bytes.
        buf.put_u8(self.session_id.len() as u8);
        buf.put_slice(&self.session_id);

        // Cipher Suites:
        // Formatted as Total Length (2 bytes) + Suite IDs (2 bytes each).
        buf.put_u16((self.cipher_suites.len() * 2) as u16);
        for &suite in &self.cipher_suites {
            buf.put_u16(suite);
        }

        // Legacy Compression Methods:
        // Always 1 byte of length (1) followed by the 'Null' method (0x00).
        buf.put_u8(1);
        buf.put_u8(0x00);

        // Extensions Block:
        // Formatted as Total Length (2 bytes) + Extension Data.
        buf.put_u16(self.extensions.len() as u16);
        buf.put_slice(&self.extensions);

        // Patch the Handshake Length:
        // We calculate the length of everything after the 3-byte placeholder.
        let total_len = (buf.len() - length_pos - 3) as u32;
        let len_bytes = total_len.to_be_bytes();
        // Copy the last 3 bytes of the big-endian u32 into the placeholder.
        buf[length_pos..length_pos + 3].copy_from_slice(&len_bytes[1..4]);

        let ext_len = self.extensions.len();
        let total_handshake_len = (buf.len() - length_pos - 3) as u32;

        tracing::debug!(
            handshake_type = "ClientHello",
            body_len = total_handshake_len,
            extensions_len = ext_len,
            total_bytes = buf.len(),
            "Serialized Handshake message"
        );
        buf.freeze()
    }

    pub fn make_client_hello(
        profile: &BrowserProfile,
        host: &str,
        public_key: &[u8; 32],
        salt: [u8; 32],
    ) -> Bytes {
        let tls_random = salt;

        let mut ext_builder = ExtensionBuilder::new();

        ext_builder.apply_profile(profile, host, public_key);
        let extensions_bytes = ext_builder.build();

        let mut session_id = BytesMut::with_capacity(32);
        session_id.put_slice(&[0u8; 32]);

        let client_hello = ClientHello {
            version: ProtocolVersion::Tls12, // Legacy version for compatibility
            random: tls_random,
            session_id: session_id.freeze(), // Standard 32-byte session ID
            cipher_suites: vec![0x1301, 0x1302, 0x1303], // TLS 1.3 suites
            extensions: extensions_bytes,
        };

        let record = TlsRecord::new(
            ContentType::Handshake,
            ProtocolVersion::Tls10,
            client_hello.serialize(),
        );

        record.serialize()
    }
}

pub struct ServerHello {
    pub version: ProtocolVersion,
    pub random: [u8; 32],
    pub session_id: Bytes,
    pub cipher_suite: u16,
    pub extensions: BytesMut,
}
impl ServerHello {
    /// Динамически создает ServerHello на основе данных из ClientHello
    pub fn from_client_hello(
        client_hello: &ClientHello,
        server_public_key: &[u8],
        salt: [u8; 32],
    ) -> Self {
        let server_random = salt;

        let selected_suite = client_hello
            .cipher_suites
            .first()
            .cloned()
            .unwrap_or(0x1301);

        let mut extensions = BytesMut::new();

        // --- Extension: Supported Versions (0x002b) ---
        extensions.put_u16(0x002b);
        extensions.put_u16(2);
        extensions.put_u16(0x0304); // TLS 1.3

        // --- Extension: Key Share (0x0033) ---
        // Структура: Type(2) + Length(2) + Group(2) + KeyLength(2) + Key(N)
        extensions.put_u16(0x0033);
        extensions.put_u16(36); // Общая длина данных расширения (2+2+32)
        extensions.put_u16(0x001d); // Named Group: x25519
        extensions.put_u16(32); // Key Length
        extensions.put_slice(server_public_key);

        Self {
            version: ProtocolVersion::Tls12,
            random: server_random,
            session_id: client_hello.session_id.clone(),
            cipher_suite: selected_suite,
            extensions,
        }
    }

    /// Оборачивает в TLS Record, принимая ключ
    pub fn make_server_hello(
        client_hello: &ClientHello,
        server_public_key: &[u8],
        salt: [u8; 32],
    ) -> Bytes {
        let server_hello = Self::from_client_hello(client_hello, server_public_key, salt);
        let handshake_payload = server_hello.serialize();

        let record = TlsRecord::new(
            ContentType::Handshake,
            ProtocolVersion::Tls12,
            handshake_payload,
        );

        record.serialize()
    }
    /// Сериализация самого сообщения Handshake (Type + Len gth + Body)
    pub fn serialize(&self) -> Bytes {
        let mut buf = BytesMut::with_capacity(256 + self.extensions.len());

        // 1. Handshake Type: 0x02 (ServerHello)
        buf.put_u8(HANDSHAKE_TYPE_SERVER_HELLO);

        // 2. Placeholder для длины (u24)
        let length_pos = buf.len();
        buf.put_bytes(0, 3);

        // 3. Тело ServerHello
        buf.put_u16(0x0303); // Legacy Version
        buf.put_slice(&self.random);

        // Session ID: Length (1 byte) + Data
        buf.put_u8(self.session_id.len() as u8);
        buf.put_slice(&self.session_id);

        // Selected Cipher Suite
        buf.put_u16(self.cipher_suite);

        // Compression: всегда 0x00
        buf.put_u8(0x00);

        // Extensions: Length (2 bytes) + Data
        buf.put_u16(self.extensions.len() as u16);
        buf.put_slice(&self.extensions);

        // 4. Патчим длину Handshake сообщения (u24)
        let total_len = (buf.len() - length_pos - 3) as u32;
        let len_bytes = total_len.to_be_bytes();
        buf[length_pos..length_pos + 3].copy_from_slice(&len_bytes[1..4]);

        let total_handshake_len = (buf.len() - length_pos - 3) as u32;
        let ext_len = self.extensions.len();
        // ИНФОРМАТИВНЫЙ ЛОГ
        tracing::debug!(
            handshake_type = "ServerHello",
            body_len = total_handshake_len,
            extensions_len = ext_len,
            total_bytes = buf.len(),
            "Serialized Handshake message"
        );

        buf.freeze() // Превращаем BytesMut в Bytes
    }
}
