use bytes::{BufMut, Bytes, BytesMut};

use crate::{
    tlseng::etype::{HANDSHAKE_TYPE_CLIENT_HELLO, HANDSHAKE_TYPE_SERVER_HELLO},
    utils::u24::U24,
};

/// TLS Content Types as defined in the TLS Record Protocol.
/// These identify what is contained within the TLS Record payload.
#[repr(u8)]
#[derive(Copy, Clone, Debug)]
pub enum ContentType {
    /// Handshake messages (e.g., ClientHello, ServerHello)
    Handshake = 0x16,
    /// Encrypted application data (the actual traffic)
    ApplicationData = 0x17,
    /// Notification messages (e.g., CloseNotify or error signals)
    Alert = 0x15,
}

impl TryFrom<u8> for ContentType {
    type Error = &'static str;
    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0x16 => Ok(ContentType::Handshake),
            0x17 => Ok(ContentType::ApplicationData),
            0x15 => Ok(ContentType::Alert),
            _ => Err("This is not ContentType"),
        }
    }
}

/// Known TLS protocol versions.
/// Note: TLS 1.3 often uses legacy versions in headers for compatibility.
#[repr(u16)]
#[derive(Copy, Clone, Debug)]
pub enum ProtocolVersion {
    Tls10 = 0x0301,
    Tls12 = 0x0303,
    Tls13 = 0x0304,
}

impl TryFrom<u16> for ProtocolVersion {
    type Error = &'static str;
    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0x0301 => Ok(ProtocolVersion::Tls10),
            0x0303 => Ok(ProtocolVersion::Tls12),
            0x0304 => Ok(ProtocolVersion::Tls13),
            _ => Err("This is not Protocol Version"),
        }
    }
}

pub struct ApplicationData {
    pub length: usize,
    pub payload: Bytes,
}

pub enum HelloType {
    Client = 0x00,
    Server = 0x01,
}

impl TryFrom<u8> for HelloType {
    type Error = &'static str;
    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0x00 => Ok(HelloType::Client),
            0x01 => Ok(HelloType::Server),
            _ => Err("This is not Hello header"),
        }
    }
}

pub struct HelloHeader {
    pub header_type: HelloType,
    pub len: U24,
    pub body: Bytes,
}

/// Represents the ClientHello Handshake message.
/// This is the first message sent by a client to initiate a TLS connection.
pub struct ClientHello {
    /// The maximum version supported (legacy field in TLS 1.3)
    pub version: ProtocolVersion,
    /// 32 bytes of client-generated entropy
    pub random: [u8; 32],
    /// Legacy session ID (used in TLS 1.3 for middlebox compatibility)
    pub session_id: Bytes,
    /// List of cryptographic ciphers the client supports
    pub cipher_suites: Vec<u16>,
    /// Opaque block of extensions generated by ExtensionBuilder
    pub extensions: Bytes,
}

impl ClientHello {
    /// Serializes the ClientHello message into its wire format.
    /// Includes the 4-byte Handshake header (Type + Length).
    pub fn serialize(&self) -> Bytes {
        let mut buf = BytesMut::with_capacity(512 + self.extensions.len());

        // Handshake Type: 0x01 (ClientHello)
        buf.put_u8(HANDSHAKE_TYPE_CLIENT_HELLO);

        // Handshake Length Placeholder:
        // Handshake messages use a 24-bit (3 byte) length field.
        let length_pos = buf.len();
        buf.put_bytes(0, 3);

        // Protocol Version:
        // For TLS 1.3, this is traditionally pinned to 0x0303 (TLS 1.2)
        // to prevent middleboxes from dropping the packet.
        buf.put_u16(0x0303);
        buf.put_slice(&self.random);

        // Legacy Session ID:
        // Formatted as Length (1 byte) + ID bytes.
        buf.put_u8(self.session_id.len() as u8);
        buf.put_slice(&self.session_id);

        // Cipher Suites:
        // Formatted as Total Length (2 bytes) + Suite IDs (2 bytes each).
        buf.put_u16((self.cipher_suites.len() * 2) as u16);
        for &suite in &self.cipher_suites {
            buf.put_u16(suite);
        }

        // Legacy Compression Methods:
        // Always 1 byte of length (1) followed by the 'Null' method (0x00).
        buf.put_u8(1);
        buf.put_u8(0x00);

        // Extensions Block:
        // Formatted as Total Length (2 bytes) + Extension Data.
        buf.put_u16(self.extensions.len() as u16);
        buf.put_slice(&self.extensions);

        // Patch the Handshake Length:
        // We calculate the length of everything after the 3-byte placeholder.
        let total_len = (buf.len() - length_pos - 3) as u32;
        let len_bytes = total_len.to_be_bytes();
        // Copy the last 3 bytes of the big-endian u32 into the placeholder.
        buf[length_pos..length_pos + 3].copy_from_slice(&len_bytes[1..4]);

        buf.freeze()
    }
}

pub struct ServerHello {
    pub version: ProtocolVersion,
    pub random: [u8; 32],
    pub session_id: Bytes,
    pub cipher_suite: u16,
    pub extensions: Bytes,
}

impl ServerHello {
    pub fn serialize(&self) -> Bytes {
        let mut buf = BytesMut::with_capacity(256 + self.extensions.len());

        // 1. Handshake Type: 0x02 (ServerHello)
        buf.put_u8(HANDSHAKE_TYPE_SERVER_HELLO);

        // 2. Placeholder для u24 длины
        let length_pos = buf.len();
        buf.put_bytes(0, 3);

        // 3. Тело ServerHello
        buf.put_u16(ProtocolVersion::Tls12 as u16); // Legacy 0x0303
        buf.put_slice(&self.random);

        // Session ID
        buf.put_u8(self.session_id.len() as u8);
        buf.put_slice(&self.session_id);

        // Выбранный Cipher Suite (в отличие от клиента, тут только ОДИН)
        buf.put_u16(self.cipher_suite);

        // Compression: всегда 0x00
        buf.put_u8(0);

        // Extensions
        buf.put_u16(self.extensions.len() as u16);
        buf.put_slice(&self.extensions);

        // 4. Патчим длину (переиспользуем твой метод)
        let total_len = (buf.len() - length_pos - 3) as u32;
        let len_bytes = total_len.to_be_bytes();
        buf[length_pos..length_pos + 3].copy_from_slice(&len_bytes[1..4]);

        buf.freeze()
    }
}

/// The TLS Record Layer structure.
/// This is the outer envelope that wraps all TLS messages sent over the wire.
#[derive(Debug)]
pub struct TlsRecord {
    /// The type of data contained (Handshake, ApplicationData, etc.)
    pub content_type: ContentType,
    /// The record layer version (usually 0x0301 for legacy support)
    pub version: ProtocolVersion,

    pub len: u16,
    /// The actual data being transported (e.g., a serialized ClientHello)
    pub payload: Bytes,
}

impl TlsRecord {
    pub fn new(content_type: ContentType, version: ProtocolVersion, payload: Bytes) -> Self {
        Self {
            content_type,
            version,
            len: payload.len() as u16,
            payload,
        }
    }

    /// Serializes the Record Layer header and payload.
    /// Wire Format: [Type (1)] [Version (2)] [Length (2)] [Payload (N)]
    pub fn serialize(&self) -> Bytes {
        let mut buf = BytesMut::with_capacity(5 + self.payload.len());

        buf.put_u8(self.content_type as u8);
        buf.put_u16(self.version as u16);
        buf.put_u16(self.payload.len() as u16);
        buf.put_slice(&self.payload);

        buf.freeze()
    }
}
