[package]
name = "netrunner-core"
version = "0.1.0"
edition = "2021"


[dependencies]
chacha20poly1305 = "0.10.1"
x25519-dalek = { version = "2.0", features = ["static_secrets"] }
aead = { version = "0.5.2", features = ["bytes"] }
hkdf = "0.12"
hmac = "0.12"
sha2 = "0.10"
bytes = "1.5"
tokio = "1.49.0"
rand = "0.10.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tracing-log = "0.2"
hex = "0.4.3"

[target.'cfg(target_os = "android")'.dependencies]
tracing-android = "0.2"